### ISSUE TITLE
rcu breaks on '/' char, TypeError: state is not a function

### ISSUE THREAD

**Issue by vujovicigor** [ractivejs/rcu#30]
This nodejs script will break and return  "TypeError: state is not a function" error:
```

 var Ractive = require('ractive');
 var rcu = require('rcu');
 rcu.init(Ractive);

 var a = rcu.parse(`<script>
    component.exports ={
      onrender: function ( options ) {
    		var aa= 2 / 3;
    	}
        ,computed:{
              paginationbuttons:function()
                  {
                      return 1/2;
                  }
          }
    }
 </script>`);

 console.log(a);
```

but if you add one more '/' it will work!:

```
 var Ractive = require('ractive');
 var rcu = require('rcu');
 rcu.init(Ractive);

 var a = rcu.parse(`<script>
    component.exports ={
      onrender: function ( options ) {
    		var aa= 2 / 3;
    		var aa= 2 / 3;
    	}
        ,computed:{
              paginationbuttons:function()
                  {
                      return 1/2;
                  }
          }
    }
 </script>`);

 console.log(a);

```

It will break if you have odd total number of '/' chars in template.

**Comment by Rich-Harris** [comment]
This was caused by an upstream bug, since fixed – can you try installing the `edge` version (`npm i rcu@edge`) and checking that it's fixed please? Thanks

**Comment by vujovicigor** [comment]
I just tried edge (rcu@0.8.2), same error :(
_TypeError: state is not a function
    at find (/home/ubuntu/nodes/webpack/node_modules/rcu/dist/rcu.umd.js:453:12)
    at match (/home/ubuntu/nodes/webpack/node_modules/rcu/dist/rcu.umd.js:474:15)
    at Object.parse (/home/ubuntu/nodes/webpack/node_modules/rcu/dist/rcu.umd.js:623:4)
    at Object.<anonymous> (/home/ubuntu/nodes/webpack/test.js:5:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)_

**Comment by vujovicigor** [comment]
It work with rcu@0.9.0-edge1 and ractive@0.8 
Thanks :)
